### ISSUE TITLE
About performance

### ISSUE THREAD

**Issue by burakkaraceylan** [jac99/FootAndBall#4]
Hello,

First of all thank you for this wonderful research. I am testing out your model and in theory it should perform better than YOLO right? However, YOLOV seems to perform a lot better using the same videos with CUDA device. Am I missing something I wonder?

Thank you,

**Comment by burakkaraceylan** [comment]
Oops my bad. Apparently, the standart YOLOV example resizes the source image.

**Comment by jac99** [comment]
Hi, our model is finetuned to long-shot videos, and performs well when size of the players and viewing direction is similar, to one presented in the clip on the main project page (from ISSIA-CNR Soccer dataset). If players have significantly different sizes, the performance will be poor. Our model does not handle well players with different sizes by design - our aim was to prepare a lightweight model, that can process high definition videos in near real time.

**Comment by burakkaraceylan** [comment]
Eventually I will test the model with a longer-shot camera (preferably seeing the whole field) I'd guess the sizes would be significantly different then. How would I go about fine-tuning the model to my specific case?

**Comment by jac99** [comment]
Sure, you can give it a try, and fine-tune the model on your dataset. The model is relatively light-weighted and it shouldn't be too time consuming to do. 
The model is agnostic to input images resolution (only the image size must be divisble by 32 as far as I remember). So you can fine-tune the model on larger images, without architecture change.

**Comment by burakkaraceylan** [comment]
Ok I will give it a go. Thank you very much!
